- name: Acte 3 - congigure csr1000 dhcp
  # On va agir sur l'hôte csr1000 dans cet acte
  hosts: csr1000
  # Passe l'étape permettant de récupérer des informations sur
  #   l'hôte pour gagner du temps
  gather_facts: false

  # Liste des tâches associées à notre Acte
  tasks:
    - name: Supression de l'ancien servuce DHCP
      cisco.ios.ios_config:
        lines:
        - no ip dhcp pool Entreprise
        

    - name: Configuration du service DHCP
      cisco.ios.ios_config:
        lines:
        - ip dhcp pool Entreprise
        - network 192.168.2.0 255.255.255.0
        - default-router 192.168.2.1
        - exit
        - service dhcp

    - name: Sauvegarde du service DHCP
      cisco.ios.ios_command:
        commands: show ip dhcp pool
      register: dhcp

    - name: Enregistre les interfaces
      copy:
        content: " {{ dhcp.stdout[0] }} "
        dest: "DHCP_POOL_{{ inventory_hostname }}.txt"

